import 'dart:core';

class en_US {
  static Map<String, String> keys() {
    return {
     translations = {
    'yes': 'Có',
    'no': 'Không',
    'cancel': 'Hủy',
    'OK': 'OK',
    'reset': 'Đặt lại',
    'success': 'Thành công',
    'error': 'Lỗi',
    'failed': 'Thất bại',
    'reload': 'Tải lại',
    'noMoreData': 'Không còn dữ liệu',
    'noData': 'Không có dữ liệu',
    'operationFailed': 'Thao tác thất bại',
    'needLoginToOperate': 'Cần đăng nhập để thao tác',
    'hasCopiedToClipboard': 'Đã sao chép vào clipboard',
    'networkError': 'Lỗi mạng, chạm để tải lại',
    'systemError': 'Lỗi hệ thống',
    'invalid': 'Không hợp lệ',
    'internalError': 'Lỗi bên trong',
    'you': 'Bạn',
    'retryHint': 'Vui lòng thử lại sau khi làm mới',
    'stop': 'Dừng',
    'attention': 'Chú ý',
    'jump': 'Nhảy',
    'deleteAll': 'Xóa tất cả',
    'connectionTimeoutHint': 'Kết nối mạng hết thời gian',
    'receiveDataTimeoutHint': 'Nhận dữ liệu mạng hết thời gian',
    'archiveError': 'Lỗi tải xuống kho lưu trữ',
    'edit': 'Sửa',
    'home': 'Trang chủ',
    'gallery': 'Bộ sưu tập',
    'setting': 'Cài đặt',
    'dawnOfaNewDay': 'Đã đến bình minh của một ngày mới!',
    'encounterMonster': 'Bạn đã gặp phải một con quái vật!',
    'encounterMonsterHint': 'Nhấn để chiến đấu trong HentaiVerse.',
    'localizedReason': 'Vui lòng xác thực để tiếp tục',
    'tap2Auth': 'Nhấn để xác thực',
    'passwordErrorHint': 'Sai mật khẩu, vui lòng thử lại',
    'TapAgainToExit': 'Nhấn lại để thoát',
    'availableUpdate': 'Bản cập nhật có sẵn!',
    'LatestVersion': 'Phiên bản mới nhất',
    'CurrentVersion': 'Phiên bản hiện tại',
    'check': 'Kiểm tra',
    'dismiss': 'Bỏ qua',
    'login': 'Đăng nhập',
    'notLoggedIn': 'Đăng nhập',
    'logout': 'Đăng xuất',
    'passwordLogin': 'Đăng nhập bằng mật khẩu',
    'cookieLogin': 'Đăng nhập bằng cookie',
    'youHaveLoggedInAs': 'Xin chào:   ',
    'cookieIsBlack': 'Cookie bị chặn',
    'cookieFormatError': 'Lỗi định dạng cookie',
    'invalidCookie': 'Đăng nhập thất bại hoặc cookie không hợp lệ',
    'loginFail': 'Đăng nhập thất bại',
    'userName': 'Tên người dùng',
    'EHUser': 'Người dùng EH',
    'password': 'Mật khẩu',
    'needCaptcha': 'Cần captcha, vui lòng đăng nhập lại bằng cookie hoặc web.',
    'userNameOrPasswordMismatch': 'Tên người dùng hoặc mật khẩu không khớp',
    'copyCookies': 'Sao chép Cookies',
    'tap2Copy': 'Nhấn để sao chép',
    'webLoginIsDisabled': 'Đăng nhập web bị vô hiệu hóa trên máy tính để bàn',
    'loginSuccess': 'Đăng nhập thành công',
    'userNameFormHint': 'Thử với cookie nếu gặp lỗi',
    'tap2Login': 'Đăng nhập',
    'parse': 'Phân tích',
    'igneousHint': 'igneous (yêu cầu EX)',
    'refreshIgneousFailed': 'Làm mới Igneous thất bại',
    'sadPanda': 'Sad Panda (không có dữ liệu). Tham khảo: https://github.com/jiangtian616/JHenTai/wiki/Common-Questions',
    'sadPandaReferLink': 'https://github.com/jiangtian616/JHenTai/wiki/Common-Questions',
    'filtered': 'Đã lọc',
    'getGallerysFailed': 'Lấy bộ sưu tập thất bại',
    'refreshGalleryFailed': 'Làm mới bộ sưu tập thất bại',
    'tabBarSetting': 'Cài đặt thanh tab',
    'jumpPageTo': 'Nhảy đến trang',
    'range': 'Phạm vi',
    'current': 'Hiện tại',
    'galleryUrlDetected': 'Tìm thấy URL bộ sưu tập trong clipboard',
    'galleryUrlDetectedHint': 'Nhấn để vào trang chi tiết',
    'read': 'Đọc',
    'download': 'Tải xuống',
    'favorite': 'Yêu thích',
    'rating': 'Đánh giá',
    'torrent': 'Torrent',
    'archive': 'Kho lưu trữ',
    'statistic': 'Thống kê',
    'similar': 'Tương tự',
    'downloading': 'Đang tải xuống',
    'resume': 'Tiếp tục',
    'pause': 'Tạm dừng',
    'finished': 'Hoàn tất',
    'update': 'Cập nhật',
    'submit': 'Gửi',
    'chooseFavorite': 'Chọn mục yêu thích',
    'asYourDefault': 'Làm mặc định',
    'Note': 'Ghi chú',
    'addNoteHint': 'Chọn vị trí trước khi thêm ghi chú',
    'uploader': 'Người tải lên',
    'allComments': 'Tất cả bình luận',
    'noComments': 'Không có bình luận',
    'lastEditedOn': 'Lần chỉnh sửa cuối cùng vào',
    'getGalleryDetailFailed': 'Lấy chi tiết bộ sưu tập thất bại',
    'invisible2User': 'Bộ sưu tập này bị ẩn đối với bạn',
    'invisibleHints': 'Bộ sưu tập này đã bị xóa hoặc không khả dụng.',
    'copyRightHints': 'Bộ sưu tập này không khả dụng do khiếu nại bản quyền bởi: ',
    'refreshGalleryDetailsFailed': 'Làm mới chi tiết bộ sưu tập thất bại',
    'failToGetThumbnails': 'Không thể lấy hình thu nhỏ',
    'favoriteGallerySuccess': 'Thêm vào mục yêu thích thành công',
    'favoriteGalleryFailed': 'Thêm vào mục yêu thích thất bại',
    'removeFavoriteSuccess': 'Xóa khỏi mục yêu thích thành công',
    'removeFavoriteFailed': 'Xóa khỏi mục yêu thích thất bại',
    'getGalleryFavoriteInfoFailed': 'Lấy thông tin yêu thích bộ sưu tập thất bại',
    'favoriteNoteSlotFullHint': 'Vị trí ghi chú yêu thích đã đầy, vui lòng xóa một số ghi chú trước',
    'ratingSuccess': 'Đánh giá thành công',
    'ratingFailed': 'Đánh giá thất bại',
    'voteTagFailed': 'Bình chọn thẻ thất bại',
    'beginToDownload': 'Bắt đầu tải xuống',
    'resumeDownload': 'Tiếp tục tải xuống',
    'pauseDownload': 'Tạm dừng tải xuống',
    'addNewTagSetSuccess': 'Thêm bộ thẻ mới thành công',
    'addNewWatchedTagSetSuccess': 'Thêm bộ thẻ theo dõi mới thành công',
    'addNewHiddenTagSetSuccess': 'Thêm bộ thẻ ẩn mới thành công',
    'addNewTagSetSuccessHint': 'Bạn có thể kiểm tra thẻ của mình tại Cài đặt->EH->Thẻ của tôi',
    'addNewTagSetFailed': 'Thêm bộ thẻ mới thất bại',
    'VisitorStatistics': 'Thống kê khách truy cập',
    'invisible2UserWithoutDonation': 'Thống kê của bộ sưu tập này bị ẩn đối với người dùng không quyên góp',
    'getGalleryStatisticsFailed': 'Lấy thống kê bộ sưu tập thất bại',
    'totalVisits': 'Tổng lượt truy cập',
    'visits': 'Lượt truy cập',
    'imageAccesses': 'Lượt truy cập hình ảnh',
    'period': 'Thời gian',
    'ranking': 'Xếp hạng',
    'score': 'Điểm số',
    'NotOnTheList': 'Không có trong danh sách',
    'getGalleryArchiveFailed': 'Lấy kho lưu trữ bộ sưu tập thất bại',
    'parseGalleryArchiveFailed': 'Phân tích thất bại, hãy đảm bảo cài đặt [Archiver Settings] trong e-hentai là [Manual Select, Manual Start (Default)]',
    'original': 'Gốc',
    'resample': 'Lấy mẫu lại',
    'beginToDownloadArchive': 'Bắt đầu tải xuống kho lưu trữ',
    'beginToDownloadArchiveHint': 'Bạn có thể kiểm tra tiến độ tại Tải xuống -> Kho lưu trữ',
    'updateGalleryError': 'Lỗi cập nhật bộ sưu tập',
    'thisGalleryHasANewVersion': 'Bộ sưu tập này có phiên bản mới',
    'hasUpdated': 'Đã cập nhật',
    'unpackingArchiveError': 'Lỗi giải nén kho lưu trữ',
    'failedToDealWith': 'Không thể xử lý',
    'hasDownloaded': 'Đã tải xuống',
    '410Hints': 'Bạn đã tải xuống quá nhiều byte trên kho lưu trữ này và cần mở khóa lại kho lưu trữ này để tiếp tục.',
    '429Hints': 'Quá nhiều yêu cầu tải xuống! Bạn nên giảm độ đồng thời tải xuống kho lưu trữ của mình.',
    'getUnpackedImagesFailedMsg': 'JHenTai không thể tải hình ảnh của kho lưu trữ này, vui lòng kiểm tra tệp cục bộ của bạn.',
    'getGalleryTorrentsFailed': 'Lấy torrent thất bại',
    'chooseArchive': 'Chọn kho lưu trữ',
    'tagSetExceedLimit': 'Không thể thêm thẻ nào nữa vì bạn đã đạt đến giới hạn',
    'useTranslation': 'Sử dụng bản dịch',
    'addTagSuccess': 'Thêm thẻ thành công',
    'addTagFailed': 'Thêm thẻ thất bại',
    'parentGallery': 'Cha',
    'blockUploaderLocally': 'Chặn người dùng cục bộ',
    'galleryUrl': 'URL bộ sưu tập',
    'title': 'Tiêu đề',
    'japaneseTitle': 'Tiêu đề tiếng Nhật',
    'category': 'Thể loại',
    'publishTime': 'Thời gian xuất bản',
    'pageCount': 'Số trang',
    'favoriteCount': 'Số lượng yêu thích',
    'ratingCount': 'Số lượng đánh giá',
    'newComment': 'Bình luận mới',
    'updateComment': 'Cập nhật bình luận',
    'commentTooShort': 'Bình luận quá ngắn',
    'sendCommentFailed': 'Gửi bình luận thất bại',
    'voteCommentFailed': 'Bình chọn bình luận thất bại',
    'voteCommentFailedHint': 'Thử kéo xuống để làm mới trang chi tiết trước',
    'unknownUser': 'Người dùng không xác định',
    'atLeast3Characters': 'Ít nhất 3 ký tự',
    'noJHenTaiHints': 'Vui lòng không đề cập đến JHenTai, cảm ơn',
    'blockUser': 'Chặn người dùng',
    'reloadImage': 'Tải lại hình ảnh',
    'parsingPage': 'Đang phân tích trang',
    'parsingURL': 'Đang phân tích URL',
    'parsePageFailed': 'Phân tích trang thất bại, nhấn để thử lại',
    'parseURLFailed': 'Phân tích URL thất bại, nhấn để thử lại',
    'loading': 'Đang tải',
    'paused': 'Đã tạm dừng',
    'exceedImageLimits': 'Vượt quá giới hạn hình ảnh',
    'ehServerError': 'Đã xảy ra lỗi do máy chủ của EH, vui lòng thử lại sau',
    'unsupportedImagePageStyle': 'JHenTai không hỗ trợ Trình xem đa trang (MPV), vui lòng chuyển sang kiểu mặc định trong e-hentai.org',
    'toNext': 'Sang trang tiếp theo',
    'toPrev': 'Sang trang trước',
    'back': 'Quay lại',
    'toggleMenu': 'Bật/tắt menu',
    'share': 'Chia sẻ',
    'save': 'Lưu vào hình ảnh',
    'account': 'Tài khoản',
    'EH': 'EH',
    'style': 'Kiểu',
    'preference': 'Tùy chọn',
    'network': 'Mạng',
    'performance': 'Hiệu suất',
    'mouseWheel': 'Bánh xe chuột',
    'advanced': 'Nâng cao',
    'cloud': 'Đám mây',
    'security': 'Bảo mật',
    'about': 'Giới thiệu',
    'accountSetting': 'Cài đặt tài khoản',
    'styleSetting': 'Cài đặt kiểu',
    'advancedSetting': 'Cài đặt nâng cao',
    'securitySetting': 'Cài đặt bảo mật',
    'ehSetting': 'Cài đặt trang EH',
    'readSetting': 'Cài đặt đọc',
    'preferenceSetting': 'Cài đặt tùy chọn',
    'downloadSetting': 'Cài đặt tải xuống',
    'networkSetting': 'Cài đặt mạng',
    'performanceSetting': 'Cài đặt hiệu suất',
    'mouseWheelSetting': 'Cài đặt bánh xe chuột',
    'site': 'Trang web',
    'redirect2Eh': 'Chuyển hướng đến EH nếu có sẵn',
    'redirect2EhHint': 'Thử tải trang chi tiết bộ sưu tập từ trang EH trước để có hiệu suất mạng tốt hơn',
    'redirectAllGallery': 'Chuyển hướng tất cả bộ sưu tập đến EH',
    'imDonorHint': 'Nếu bạn là người quyên góp, bạn có thể bật tính năng này để giúp bạn truy cập bộ sưu tập trong trang EX',
    'profileSetting': 'Cài đặt hồ sơ',
    'chooseProfileHint': 'Chọn hồ sơ được sử dụng trong JHenTai',
    'siteSetting': 'Cài đặt trang web',
    'siteSettingHint': 'Chỉnh sửa cài đặt trang web trong e-hentai',
    'showCookie': 'Cookie',
    'redirect2EH': 'Chuyển hướng đến trang EH nếu có sẵn',
    'redirect2Hints': 'Sẽ thử phân tích trang EH trước',
    'pleaseLogInToOperate': 'Vui lòng đăng nhập để thao tác',
    'imageLimits': 'Hạn mức hình ảnh',
    'resetCost': 'Nhấn giữ để đặt lại, chi phí',
    'assets': 'Tài sản',
    'isNotDonator': 'Người dùng không quyên góp không thể xem hạn mức',
    'fetchImageQuotaFailed': 'Lấy hạn mức hình ảnh thất bại',
    'myTags': 'Thẻ của tôi',
    'myTagsHint': 'Quản lý thẻ theo dõi và thẻ ẩn trực tuyến',
    'localTags': 'Thẻ cục bộ',
    'localTagsHint': 'Thẻ lọc bổ sung',
    'localTagsHint2': 'Bộ sưu tập có những thẻ này sẽ bị ẩn',
    'addLocalTags': 'Thêm thẻ',
    'hidden': 'Ẩn',
    'nope': 'Không',
    'getTagSetFailed': 'Lấy bộ thẻ thất bại',
    'updateTagSetFailed': 'Cập nhật bộ thẻ thất bại',
    'updateTagFailed': 'Cập nhật thẻ thất bại',
    'deleteTagSuccess': 'Xóa thẻ thành công',
    'deleteTagFailed': 'Xóa thẻ thất bại',
    'addLocalTagHint': 'Tìm kiếm để thêm thẻ mới',
    'selectedProfile': 'Hồ sơ đã chọn',
    'resetIfSwitchSite': 'Sẽ được đặt lại nếu chuyển trang',
    'addHostMapping': 'Thêm ánh xạ máy chủ',
    'layoutMode': 'Chế độ bố cục',
    'mobileLayoutV2Name': 'Điện thoại',
    'mobileLayoutV2Desc': 'Một cột',
    'mobileLayoutName': 'Điện thoại (cũ)',
    'mobileLayoutDesc': 'Ngừng bảo trì',
    'tabletLayoutV2Name': 'Máy tính bảng',
    'tabletLayoutV2Desc': 'Hai cột',
    'tabletLayoutName': 'Máy tính bảng (cũ)',
    'tabletLayoutDesc': 'Ngừng bảo trì',
    'desktopLayoutName': 'Máy tính để bàn',
    'desktopLayoutDesc': 'Hai cột với thanh tab bên trái, hỗ trợ bàn phím',
    'enableTagZHTranslation': 'Dịch tên thẻ sang tiếng Trung',
    'version': 'Phiên bản',
    'downloadTagTranslationHint': 'Đang tải dữ liệu..., đã tải xuống: ',
    'zhTagSearchOrderOptimization': 'Quy tắc sắp xếp tự động hoàn thành thẻ tiếng Trung',
    'zhTagSearchOrderOptimizationHint': 'Sắp xếp thông minh theo mặc định và sắp xếp theo tần suất nếu bật',
    'themeMode': 'Chế độ chủ đề',
    'dark': 'Tối',
    'light': 'Sáng',
    'followSystem': 'Theo hệ thống',
    'themeColor': 'Màu chủ đề',
    'listStyle': 'Kiểu danh sách bộ sưu tập (Toàn cục)',
    'flat': 'Phẳng',
    'flatWithoutTags': 'Phẳng (Không có thẻ)',
    'listWithoutTags': 'Thẻ (Không có thẻ)',
    'listWithTags': 'Thẻ',
    'waterfallFlowSmall': 'Dòng thác (Nhỏ)',
    'waterfallFlowMedium': 'Dòng thác (Trung bình)',
    'waterfallFlowBig': 'Dòng thác (Lớn)',
    'crossAxisCountInWaterFallFlow': 'Số cột dòng thác',
    'pageListStyle': 'Kiểu danh sách bộ sưu tập (Trang)',
    'crossAxisCountInGridDownloadPageForGroup': 'Số cột lưới trang tải xuống (Nhóm)',
    'crossAxisCountInGridDownloadPageForGallery': 'Số cột lưới trang tải xuống (Bộ sưu tập)',
    'crossAxisCountInDetailPage': 'Số cột hình thu nhỏ trang chi tiết',
    'global': 'Toàn cục',
    'auto': 'Tự động',
    'moveCover2RightSide': 'Di chuyển ảnh bìa sang bên phải',
    'coverStyle': 'Kiểu ảnh bìa',
    'cover': 'Ảnh bìa',
    'adaptive': 'Điều chỉnh',
    'simpleDashboardMode': 'Trang chủ đơn giản',
    'simpleDashboardModeHint': 'Ẩn bảng xếp hạng và phổ biến',
    'hideBottomBar': 'Ẩn thanh dưới cùng',
    'hideScroll2TopButton': 'Ẩn nút cuộn lên trên',
    'whenScrollUp': 'Khi cuộn lên',
    'whenScrollDown': 'Khi cuộn xuống',
    'preloadGalleryCover': 'Tải trước ảnh bìa bộ sưu tập',
    'preloadGalleryCoverHint': 'Tải trước ảnh bìa của các bộ sưu tập chưa được hiển thị trên trang',
    'enableSwipeBackGesture': 'Bật cử chỉ vuốt trở lại',
    'enableLeftMenuDrawerGesture': 'Bật cử chỉ ngăn kéo menu bên trái',
    'enableQuickSearchDrawerGesture': 'Bật cử chỉ ngăn kéo tìm kiếm nhanh',
    'drawerGestureEdgeWidth': 'Độ rộng cạnh cử chỉ ngăn kéo',
    'alwaysShowScroll2TopButton': 'Luôn hiển thị nút cuộn lên trên',
    'enableDefaultFavorite': 'Bật mục yêu thích mặc định',
    'enableDefaultFavoriteHint': 'Nhấn giữ để chọn lại',
    'enableDefaultTagSet': 'Bật bộ thẻ mặc định',
    'enableDefaultTagSetHint': 'Nhấn giữ để chọn lại',
    'disableDefaultTagSetHint': 'Chọn thủ công',
    'launchInFullScreen': 'Khởi chạy ở chế độ toàn màn hình',
    'launchInFullScreenHint': 'Chuyển đổi thủ công bằng F11',
    'disableDefaultFavoriteHint': 'Chọn thủ công',
    'searchBehaviour': 'Hành vi tìm kiếm',
    'inheritAll': 'Kế thừa tất cả',
    'inheritAllHint': 'Sử dụng tùy chọn tìm kiếm cuối cùng cho tìm kiếm tiếp theo',
    'inheritPartially': 'Kế thừa một phần',
    'inheritPartiallyHint': 'Sử dụng tùy chọn tìm kiếm cuối cùng cho tìm kiếm tiếp theo (ngoại trừ ngôn ngữ và thể loại)',
    'none': 'Không',
    'noneHint': 'Sử dụng tùy chọn tìm kiếm mặc định cho tìm kiếm tiếp theo',
    'showAllGalleryTitles': 'Hiển thị tất cả tiêu đề bộ sưu tập',
    'showAllGalleryTitlesHint': 'Hiển thị cả tiêu đề gốc và tiếng Nhật nếu có',
    'showGalleryTagVoteStatus': 'Hiển thị trạng thái bình chọn thẻ bộ sưu tập',
    'showGalleryTagVoteStatusHint': 'Bao gồm sự tự tin, hoài nghi và không chính xác',
    'showComments': 'Hiển thị bình luận',
    'showAllComments': 'Hiển thị tất cả bình luận',
    'showAllCommentsHint': 'Theo mặc định, chỉ có 45 bình luận có điểm cao nhất và 5 bình luận gần đây nhất sẽ được hiển thị',
    'addTag': 'Thêm thẻ',
    'addTagHint': 'Nhập thẻ mới, phân tách bằng dấu phẩy',
    'themeColorSettingHint': 'Gán màu khác nhau cho chủ đề sáng và tối',
    'preview': 'Xem trước',
    'preset': 'Mặc định',
    'custom': 'Tùy chỉnh',
    'maxGalleryNum4Animation': 'Số lượng bộ sưu tập tối đa cho hoạt ảnh danh sách trong trang tải xuống',
    'maxGalleryNum4AnimationHint': 'Vô hiệu hóa hoạt ảnh cho các nhóm có nhiều bộ sưu tập hơn giá trị này (đối với kiểu danh sách)',
    'wheelScrollSpeed': 'Tốc độ cuộn bánh xe',
    'ineffectiveInGalleryPage': 'Hiện tại không hiệu quả trong trang bộ sưu tập.',
    'enableDomainFronting': 'Bật Domain Fronting',
    'bypassSNIBlocking': 'Bỏ qua chặn SNI',
    'hostMapping': 'Ánh xạ máy chủ',
    'hostMappingHint': 'Được sử dụng cho domain fronting',
    'proxyAddress': 'Địa chỉ proxy',
    'proxyAddressHint': 'Nếu bạn sử dụng máy chủ proxy, hãy đảm bảo thiết lập chính xác',
    'saveSuccess': 'Lưu thành công',
    'saveFailed': 'Lưu thất bại',
    'updateSuccess': 'Cập nhật thành công',
    'connectTimeout': 'Hết thời gian kết nối',
    'receiveTimeout': 'Hết thời gian nhận dữ liệu',
    'pageCacheMaxAge': 'Thời gian hết hạn bộ nhớ cache trang',
    'pageCacheMaxAgeHint': 'Bạn có thể cập nhật bộ nhớ cache bằng cách làm mới trang',
    'cacheImageExpireDuration': 'Thời gian hết hạn bộ nhớ cache hình ảnh',
    'cacheImageExpireDurationHint': 'Xóa bộ nhớ cache hình ảnh tự động sau khi khởi chạy ứng dụng',
    'oneMinute': '1 Phút',
    'tenMinute': '10 Phút',
    'oneHour': '1 Giờ',
    'oneDay': '1 Ngày',
    'threeDay': '3 Ngày',
    'enableLogging': 'Bật ghi nhật ký',
    'enableVerboseLogging': 'Bật ghi nhật ký chi tiết',
    'openLog': 'Mở nhật ký',
    'clearLogs': 'Xóa nhật ký',
    'clearImagesCache': 'Xóa bộ nhớ cache hình ảnh',
    'longPress2Clear': 'Nhấn giữ để xóa',
    'checkUpdateAfterLaunchingApp': 'Kiểm tra cập nhật sau khi khởi chạy ứng dụng',
    'checkClipboard': 'Kiểm tra URL bộ sưu tập trong clipboard',
    'clearPageCache': 'Xóa bộ nhớ cache trang',
    'clearSuccess': 'Xóa thành công',
    'superResolution': 'Độ phân giải siêu cao hình ảnh',
    'stopSuperResolution': 'Dừng độ phân giải siêu cao',
    'deleteSuperResolvedImage': 'Xóa hình ảnh độ phân giải siêu cao',
    'superResolveOriginalImageHint': 'Xử lý hình ảnh gốc tốn nhiều thời gian, không gian và hiệu suất hơn, bạn có chắc muốn tiếp tục không?',
    'verityAppLinks4Android12': 'Xác minh liên kết ứng dụng (Android 12+)',
    'verityAppLinks4Android12Hint': 'Đối với Android 12+, bạn cần thêm liên kết thủ công vào các liên kết đã được xác minh để mở JHenTai trong các ứng dụng của bên thứ ba',
    'noImageMode': 'Chế độ không hình ảnh',
    'exportData': 'Xuất dữ liệu',
    'exportDataHint': 'Xuất cấu hình, quy tắc chặn và lịch sử',
    'selectExportItems': 'Chọn mục xuất',
    'importData': 'Nhập dữ liệu',
    'importDataHint': 'Ứng dụng sẽ tự động tắt sau khi nhập để áp dụng cấu hình mới nhất',
    'hostDataSource': 'Không cần thay đổi theo mặc định.\nNguồn dữ liệu: https://dns.google/',
    'proxySetting': 'Cài đặt proxy',
    'proxyType': 'Loại proxy',
    'systemProxy': 'Hệ thống',
    'httpProxy': 'HTTP',
    'socks5Proxy': 'SOCKS5',
    'socks4Proxy': 'SOCKS4',
    'directProxy': 'TRỰC TIẾP',
    'address': 'Địa chỉ',
    'enablePasswordAuth': 'Bật xác thực mật khẩu',
    'enableBiometricAuth': 'Bật xác thực sinh trắc học',
    'enableAuthOnResume': 'Bật xác thực khi tiếp tục',
    'enableAuthOnResumeHints': 'Trì hoãn 3 giây',
    'enableBlurBackgroundApp': 'Bật làm mờ trang khi chuyển sang nền',
    'hideImagesInAlbum': 'Ẩn hình ảnh trong album',
    'hideImagesInAlbumHints': 'Nếu bạn thay đổi đường dẫn tải xuống mặc định, bạn cần tạo .nomedia thủ công',
    'enableImmersiveMode': 'Bật chế độ Immersive',
    'keepScreenAwakeWhenReading': 'Giữ màn hình sáng khi đọc',
    'enableCustomReadBrightness': 'Bật độ sáng tùy chỉnh khi đọc',
    'spaceBetweenImages': 'Khoảng cách giữa các hình ảnh',
    'enableImmersiveHint': 'Ẩn thanh hệ thống',
    'enableImmersiveHint4Windows': 'Ẩn thanh tiêu đề',
    'deviceOrientation': 'Hướng máy',
    'landscape': 'Ngang',
    'portrait': 'Dọc',
    'readDirection': 'Hướng đọc',
    'notchOptimization': 'Tối ưu hóa tai thỏ',
    'notchOptimizationHint': 'Thêm phần đệm trước hình ảnh đầu tiên để tránh tai thỏ và thanh trạng thái',
    'imageRegionWidthRatio': 'Tỷ lệ chiều rộng vùng hình ảnh',
    'gestureRegionWidthRatio': 'Tỷ lệ chiều rộng vùng cử chỉ',
    'useThirdPartyViewer': 'Sử dụng trình xem tùy chỉnh',
    'thirdPartyViewerPath': 'Đường dẫn trình xem tùy chỉnh (Tệp thực thi)',
    'showThumbnails': 'Hiển thị hình thu nhỏ',
    'showScrollBar': 'Hiển thị thanh cuộn',
    'showStatusInfo': 'Hiển thị trạng thái ở dưới cùng',
    'autoModeInterval': 'Khoảng thời gian tự động',
    'autoModeStyle': 'Kiểu chế độ tự động',
    'scroll': 'Cuộn',
    'turnPage': 'Đổi trang',
    'top2bottomList': 'Từ trên xuống dưới (Liền mạch)',
    'left2rightSinglePage': 'Từ trái sang phải (Một trang)',
    'left2rightSinglePageFitWidth': 'Từ trái sang phải (Phù hợp chiều rộng)',
    'right2leftSinglePage': 'Từ phải sang trái (Một trang)',
    'right2leftSinglePageFitWidth': 'Từ phải sang trái (Phù hợp chiều rộng)',
    'left2rightDoubleColumn': 'Từ trái sang phải (Hai cột)',
    'right2leftDoubleColumn': 'Từ phải sang trái (Hai cột)',
    'left2rightList': 'Từ trái sang phải (Liền mạch)',
    'right2leftList': 'Từ phải sang trái (Liền mạch)',
    'enablePageTurnByVolumeKeys': 'Sử dụng phím âm lượng để đổi trang',
    'enablePageTurnAnime': 'Bật hoạt ảnh đổi trang',
    'enableDoubleTapToScaleUp': 'Bật nhấn đúp để phóng to',
    'enableTapDragToScaleUp': 'Bật nhấn kéo để phóng to',
    'enableBottomMenu': 'Bật menu dưới cùng',
    'reverseTurnPageDirection': 'Đảo ngược hướng đổi trang',
    'disableGestureWhenScrolling': 'Vô hiệu hóa cử chỉ khi cuộn',
    'disablePageTurningOnTap': 'Vô hiệu hóa đổi trang khi chạm',
    'turnPageMode': 'Chế độ đổi trang',
    'turnPageModeHint': 'Sang màn hình tiếp theo hoặc hình ảnh tiếp theo',
    'enableImageMaxKilobytes': 'Bật nén hình ảnh',
    'imageMaxKilobytes': 'Kích thước tối đa hình ảnh',
    'imageMaxKilobytesHint': 'Hình ảnh lớn hơn kích thước này sẽ bị nén',
    'image': 'Hình ảnh',
    'screen': 'Màn hình',
    'preloadDistanceInOnlineMode': 'Khoảng cách tải trước (Trực tuyến)',
    'preloadDistanceInLocalMode': 'Khoảng cách tải trước (Cục bộ)',
    'ScreenHeight': 'Màn hình',
    'preloadPageCount': 'Số trang tải trước (Trực tuyến)',
    'preloadPageCountInLocalMode': 'Số trang tải trước (Cục bộ)',
    'continuousScroll': 'Cuộn liên tục',
    'continuousScrollHint': 'Nối nhiều hình ảnh',
    'doubleColumn': 'Hai cột',
    'displayFirstPageAlone': 'Hiển thị trang đầu tiên riêng',
    'displayFirstPageAloneGlobally': 'Hiển thị trang đầu tiên riêng (Toàn cục)',
    'toggleFullScreen': 'Bật/tắt toàn màn hình',
    'enableAutoScaleUp': 'Bật tự động phóng to hình ảnh dài',
    'enableAutoScaleUpHints': 'Làm cho chiều rộng hình ảnh giống với chiều rộng màn hình',
    'showR18GImageDirectly': 'Hiển thị hình ảnh R18G trực tiếp',
    'defaultTab': 'Tab mặc định',
    'showUtcTime': 'Hiển thị thời gian UTC cho bộ sưu tập',
    'showDawnInfo': 'Hiển thị sự kiện bình minh mới',
    'showEncounterMonster': 'Hiển thị sự kiện gặp quái vật hentaiVerse',
    'logList': 'Danh sách nhật ký',
    'downloadSuperResolutionModelHint': 'Tải xuống mô hình từ Github',
    'modelDirectoryPath': 'Đường dẫn thư mục mô hình',
    'upSamplingScale': 'Tỷ lệ lấy mẫu tăng',
    'modelType': 'Chọn mô hình',
    'x4plusHint': 'Chiếm nhiều không gian hơn nhưng nhanh hơn trong hầu hết thời gian',
    'x4plusAnimeHint': 'Chiếm ít không gian hơn nhưng chậm hơn trong hầu hết thời gian',
    'enable4OnlineReading': 'Xử lý tự động khi đọc trực tuyến',
    'local': 'Cục bộ',
    'reDownload': 'Tải lại',
    'delete': 'Xóa',
    'deleteTask': 'Chỉ xóa tác vụ',
    'deleteTaskAndImages': 'Xóa tác vụ và hình ảnh',
    'unlocking': 'Đang mở khóa',
    'unlocked': 'Đã mở khóa',
    'parsingDownloadPageUrl': 'Đang phân tích Ⅰ',
    'parsedDownloadPageUrl': 'Đang phân tích Ⅰ',
    'parsingDownloadUrl': 'Đang phân tích Ⅱ',
    'parsedDownloadUrl': 'Đang phân tích Ⅱ',
    'waitingIsolate': 'Đang chờ',
    'downloaded': 'Đã tải xuống',
    'downloadFailed': 'Tải xuống thất bại',
    'unpacking': 'Đang giải nén',
    'completed': 'Hoàn thành',
    'needReUnlock': 'Cần mở khóa lại',
    'reUnlock': 'Mở khóa lại',
    'reUnlockHint': 'Chú ý! Mở khóa lại cần mua lại kho lưu trữ này.',
    'downloadHelpInfo': 'Nếu bạn không thể tải xuống và tìm thấy lỗi như bảng không tồn tại trong nhật ký, vui lòng gỡ cài đặt ứng dụng hiện tại và cài đặt lại.',
    'localGalleryHelpInfo': 'Tải bộ sưu tập chưa được tải xuống bởi JHenTai. Thêm cấu hình trong Cài đặt tải xuống -> Đường dẫn quét bộ sưu tập bổ sung và sau đó làm mới.',
    'localGalleryHelpInfo4iOSAndMacOS': 'Tải bộ sưu tập chưa được tải xuống bởi JHenTai. Đặt bộ sưu tập của bạn vào đường dẫn tải xuống mặc định và sau đó làm mới',
    'deleteLocalGalleryHint': 'Xóa tệp cục bộ của bạn',
    'priority': 'Ưu tiên',
    'highest': 'Cao nhất',
    'default': 'Mặc định',
    'newGalleryCount': 'Số lượng bộ sưu tập mới',
    'changePriority': 'Thay đổi ưu tiên',
    'changeGroup': 'Thay đổi nhóm',
    'chooseGroup': 'Chọn nhóm',
    'renameGroup': 'Đổi tên nhóm',
    'deleteGroup': 'Xóa nhóm',
    'existingGroup': 'Nhóm hiện có',
    'groupName': 'Tên nhóm',
    'drag2sort': 'Kéo để sắp xếp',
    'switch2GridMode': 'Chuyển sang chế độ lưới',
    'switch2ListMode': 'Chuyển sang chế độ danh sách',
    'multiSelect': 'Chọn nhiều',
    'multiSelectHint': 'Nhấn để chọn',
    'resumeAllTasks': 'Tiếp tục tất cả tác vụ',
    'pauseAllTasks': 'Tạm dừng tất cả tác vụ',
    'requireDownloadComplete': 'Yêu cầu tải xuống hoàn tất',
    'operationHasCompleted': 'Thao tác đã hoàn tất',
    'operationInProgress': 'Thao tác đang được tiến hành',
    'startProcess': 'Bắt đầu quá trình',
    'multiReDownloadHint': 'Bạn sẽ tải lại tất cả các bộ sưu tập đã chọn.',
    'multiChangeGroupHint': 'Bạn sẽ thay đổi nhóm của tất cả các bộ sưu tập đã chọn.',
    'multiDeleteHint': 'Bạn sẽ xóa tất cả các bộ sưu tập đã chọn.',
    'peakHoursHint': 'Tải xuống các tệp gốc trong giờ cao điểm yêu cầu GP và bạn không đủ, tải xuống bị tạm dừng.',
    'oldGalleryHint': 'Tải xuống các tệp gốc của bộ sưu tập này yêu cầu GP và bạn không đủ.',
    'exceedLimitHint': 'Bạn đã đạt đến giới hạn hình ảnh và không có đủ GP để mua hạn mức tải xuống.',
    'deleteUpdatingDependentHint': 'Bản cập nhật của một bộ sưu tập khác phụ thuộc vào bộ sưu tập hiện tại, bạn nên xóa sau khi cập nhật hoàn tất.',
    'migrateToDownload': 'Chuyển đến 「Tải xuống」',
    'refresh': 'Làm mới',
    'simpleSearch': 'Đơn giản',
    'regexSearch': 'Regex',
    'searchConfig': 'Cấu hình tìm kiếm',
    'addTabBar': 'Thêm thanh tab',
    'updateTabBar': 'Cập nhật thanh tab',
    'addQuickSearch': 'Thêm',
    'updateQuickSearch': 'Cập nhật',
    'filter': 'Bộ lọc',
    'tabBarName': 'Tên thanh tab',
    'quickSearchName': 'Tên tìm kiếm nhanh',
    'pleaseInputValidName': 'Vui lòng nhập tên hợp lệ',
    'sameNameExists': 'Tên đã tồn tại',
    'sameConfigExists': 'Cấu hình đã tồn tại',
    'searchType': 'Loại tìm kiếm',
    'popular': 'Phổ biến',
    'ranklist': 'Bảng xếp hạng',
    'ranklistBoard': 'Bảng xếp hạng',
    'watched': 'Đã xem',
    'history': 'Lịch sử',
    'keyword': 'Từ khóa',
    'orderBy': 'Sắp xếp theo',
    'favoritedTime': 'Thời gian yêu thích',
    'publishedTime': 'Thời gian đăng tải',
    'backspace2DeleteTag': 'Nhấn backspace để xóa thẻ',
    'searchGalleryName': 'Tìm kiếm tên gallery',
    'searchGalleryTags': 'Tìm kiếm thẻ gallery',
    'searchGalleryDescription': 'Tìm kiếm mô tả gallery',
    'onlySearchExpungedGalleries': "Chỉ tìm kiếm gallery đã bị xóa",
    'onlyShowGalleriesWithTorrents': 'Chỉ hiển thị gallery có torrent',
    'searchLowPowerTags': 'Tìm kiếm thẻ thấp',
    'searchDownVotedTags': 'Tìm kiếm thẻ bị bỏ phiếu thấp',
    'pageAtLeast': 'Trang ít nhất',
    'pageAtMost': 'Trang nhiều nhất',
    'pagesBetween': 'Trang giữa',
    'pageRangeSelectHint': 'min <= 1000, max >= 10\nmin/max <= 0.8, max-min >= 20',
    'to': 'đến',
    'minimumRating': 'Đánh giá tối thiểu',
    'disableFilterForLanguage': 'Vô hiệu hóa bộ lọc ngôn ngữ',
    'disableFilterForUploader': 'Vô hiệu hóa bộ lọc người đăng',
    'disableFilterForTags': 'Vô hiệu hóa bộ lọc thẻ',
    'searchName': 'Tìm kiếm tên',
    'searchTags': 'Tìm kiếm thẻ',
    'searchNote': 'Tìm kiếm ghi chú',
    'allTime': 'Tất cả thời gian',
    'year': 'Năm',
    'month': 'Tháng',
    'day': 'Ngày',
    'favoriteHint': 'Định nghĩa: thẻ/tên/bình luận/yêu thích',

    
    'getPopularListFailed': 'Lấy danh sách phổ biến thất bại',

    
    'getRanklistFailed': 'Lấy bảng xếp hạng thất bại',
    'getSomeOfGalleriesFailed': 'Lấy một số gallery thất bại',

    'getHistoryGalleriesFailed': 'Lấy lịch sử gallery thất bại',

    'search': 'Tìm kiếm',
    'searchFailed': 'Tìm kiếm thất bại',
    'fileSearchFailed': 'Tìm kiếm file thất bại',
    'tab': 'Tab',
    'openGallery': 'Mở gallery',
    'tapChip2Delete': 'Nhấn để xóa\nGiữ lâu để xóa tất cả',
    'accurateCountTemplate': '%s kết quả',
    'hundredsOfCountTemplate': 'Hàng trăm kết quả',
    'thousandsOfCountTemplate': 'Hàng nghìn kết quả',


    'author': 'Tác giả',
    'Q&A': 'Câu hỏi và trả lời',
    'telegramHint': 'Bạn có thể hỏi câu hỏi trên github trước',

    'downloadPath': 'Đường dẫn tải xuống',
    'changeDownloadPathHint': 'Giữ lâu để thay đổi (không sử dụng thẻ SD hoặc đường dẫn hệ thống). Sẽ sao chép gallery đã tải xuống tự động và giữ file cũ. Nếu gặp lỗi, thử đặt lại.',
    'resetDownloadPath': 'Đặt lại đường dẫn tải xuống',
    'extraGalleryScanPath': 'Đường dẫn quét gallery thêm',
    'extraGalleryScanPathHint': 'Để quét và tải gallery địa phương',
    'singleImageSavePath': 'Đường dẫn lưu hình đơn',
    'downloadOriginalImage': 'Hình gốc',
    'downloadOriginalImageByDefault': 'Chọn hình gốc theo mặc định',
    'originalImage': 'Gốc',
    'resampleImage': 'Lấy mẫu lại',
    'defaultGalleryGroup': 'Nhóm gallery mặc định',
    'defaultArchiveGroup': 'Nhóm lưu trữ mặc định',
    'never': 'Không bao giờ',
    'manual': 'Thủ công',
    'always': 'Luôn luôn',
    'longPress2Reset': 'Giữ lâu để đặt lại',
    'needPermissionToChangeDownloadPath': 'Cần quyền để thay đổi đường dẫn tải xuống',
    'invalidPath': 'Đường dẫn không hợp lệ. Tránh sử dụng thẻ SD',

    'downloadTaskConcurrency': 'Số lượng tác vụ tải xuống đồng thời',
    'needRestart': 'Cần khởi động lại',
    'speedLimit': 'Giới hạn tốc độ',
    'speedLimitHint': 'Không tải xuống quá nhanh',
    'per': 'trên',
    'images': 'hình ảnh',
    'downloadTimeout': 'Thời gian chờ tải xuống',
    'downloadAllGallerysOfSamePriority': 'Tải xuống tất cả gallery cùng mức độ ưu tiên',
    'downloadAllGallerysOfSamePriorityHint': 'Tải xuống 1 gallery cùng lúc trong 1 nhóm có mức độ ưu tiên cao nhất theo mặc định',
    'alwaysUseDefaultGroup': 'Luôn sử dụng nhóm mặc định',
    'enableStoreMetadataForRestore': 'Bật lưu trữ siêu dữ liệu để khôi phục',
    'enableStoreMetadataForRestoreHint': 'Nếu tắt tính năng này, bạn không thể khôi phục tác vụ tải xuống',
    'archiveDownloadIsolateCount': 'Số lượng luồng tải xuống lưu trữ',
    'archiveDownloadIsolateCountHint': 'Tổng số luồng cho tất cả tác vụ cần nhỏ hơn 10, nếu không tải xuống sẽ thất bại',
    'manageArchiveDownloadConcurrency': 'Quản lý số lượng tác vụ tải xuống lưu trữ đồng thời',
    'manageArchiveDownloadConcurrencyHint': 'Lưu trữ sẽ chờ cho đến khi có đủ luồng để tải xuống',
    'deleteArchiveFileAfterDownload': 'Xóa file lưu trữ sau khi tải xuống',
    'restoreDownloadTasks': 'Khôi phục tác vụ tải xuống',
    'restoreDownloadTasksHint': 'Khôi phục tác vụ tải xuống bằng siêu dữ liệu',
    'restoreDownloadTasksSuccess': 'Khôi phục tác vụ tải xuống thành công',
    'restoredCount': 'Số lượng tác vụ đã khôi phục',
    'restoredGalleryCount': 'Số lượng gallery đã khôi phục',
    'restoredArchiveCount': 'Số lượng lưu trữ đã khôi phục',
    'restoreTasksAutomatically': 'Khôi phục tác vụ tự động',
    'restoreTasksAutomaticallyHint': 'Khôi phục tác vụ tự động khi ứng dụng được khởi chạy',
    'brokenDownloadPathHint': 'Đường dẫn tải xuống của bạn có vẻ bị hỏng, chức năng tải xuống có thể không hiệu quả',
    'brokenExtraScanPathHint': 'Đường dẫn quét gallery địa phương mặc định của bạn có vẻ bị hỏng, gallery địa phương có thể không được nhận diện',


    'setPasswordHint': 'Vui lòng nhập mật khẩu của bạn',
    'confirmPasswordHint': 'Vui lòng nhập lại mật khẩu của bạn',
    'passwordNotMatchHint': 'Mật khẩu không khớp, vui lòng thử lại',


    'serverCondition': 'Điều kiện máy chủ',
    'configSync': 'Đồng bộ hóa cấu hình',
    'configSyncHint': 'Lưu trữ dữ liệu cấu hình của bạn trên đám mây (tối đa 50 mục)',
    'upload2cloud': 'Tải lên đám mây',
    'upload2cloudHint': 'Tải lên cấu hình địa phương hiện tại của bạn',
    'tap2upload': 'Nhấn để tải lên',
    'copyIdentificationCodeSuccess': 'Tải lên thành công. Mã nhận dạng đã được sao chép',
    'copyShareCode': 'Sao chép mã chia sẻ',
    'import': 'Nhập',
    'save2Local': 'Lưu vào địa phương',
    'readIndexRecord': 'Đọc tiến trình',
    'quickSearch': 'Tìm kiếm nhanh cấu hình',
    'blockRules': 'Quy tắc chặn',
    'searchHistory': 'Lịch sử tìm kiếm',
    'galleryHistory': 'Lịch sử gallery',


    'configureBlockRuleFailed': 'Cấu hình quy tắc chặn thất bại',
    'removeBlockRuleFailed': 'Xóa quy tắc chặn thất bại',
    'inputNumberHint': 'Vui lòng nhập số chính xác',
    'inputRegexHint': 'Vui lòng nhập biểu thức chính quy chính xác',
    'blockingRules': 'Quy tắc chặn',
    'blockingRulesHint': 'Quy tắc chặn bổ sung cho gallery và bình luận',
    'blockingTarget': 'Mục tiêu chặn',
    'blockingAttribute': 'Thuộc tính chặn',
    'blockingPattern': 'Mẫu chặn',
    'blockingExpression': 'Biểu thức chặn',
    'contain': 'Chứa',
    'notContain': 'Không chứa',
    'regex': 'Biểu thức chính quy',
    'comment': 'Bình luận',
    'tag': 'Thẻ',
    'userId': 'Mã người dùng',
    'content': 'Nội dung',
    'incompleteInformation': 'Thông tin không đầy đủ',
    'noBlockingRuleHint': 'Thêm ít nhất 1 quy tắc',
    'notSameBlockingRuleTargetHint': 'Tất cả quy tắc con phải có cùng mục tiêu chặn',
    'blockingRuleHelp': '''
Mục tiêu chặn: Lọc gallery trên trang danh sách hoặc lọc bình luận trên trang chi tiết. Tất cả quy tắc con dưới cùng một quy tắc phải có cùng mục tiêu chặn.
Thuộc tính chặn: Xác định thuộc tính của mục tiêu dựa trên quy tắc viết để chặn.
Mẫu chặn: Sử dụng biểu thức chính quy cho các kịch bản phức tạp.
Biểu thức chặn: Chuỗi đơn giản hoặc biểu thức chính quy.
Lưu ý 1: Các quy tắc khác nhau có mối quan hệ OR (||), trong khi tất cả quy tắc con dưới cùng một quy tắc có mối quan hệ AND (&&).
Lưu ý 2: Khi chặn thẻ, quy tắc sẽ kiểm tra từng thẻ trong gallery, biểu thức nên được viết cho một thẻ đơn.
Lưu ý 3: Khi chặn thẻ, bạn cần chỉ định thẻ đầy đủ với không gian tên nếu sử dụng quy tắc '='.
Ví dụ 1: Chặn gallery có thẻ "yaoi" và không có thẻ "tomgirl" —— Gallery Tag Contain yaoi && Gallery Tag NotContain tomgirl
Ví dụ 2: Chặn bình luận có điểm không vượt quá 10 —— Comment Score <= 10
''',

    
    'quickSearch': 'Tìm kiếm nhanh',

    'seeAll': 'Tất cả',
    'newest': 'Mới nhất',

    'outdated': 'Lỗi thời',

    'warningImageHint': 'Hình ảnh R18G, nhấn để xem',

    'chooseTagSet': 'Chọn tập thẻ',

    'language': 'Ngôn ngữ',
    'artist': 'Họa sĩ',
    'character': 'Nhân vật',
    'female': 'Nữ',
    'male': 'Nam',
    'parody': 'Nhái',
    'group': 'Nhóm',
    'mixed': 'Trộn',
    'Coser': 'Coser',
    'cosplayer': 'Cosplayer',
    'reclass': 'Đổi lớp',
    'temp': 'Tạm',
    'other': 'Khác'
    };
  }
}
